_ss_11:

        .byte $00,$00,$00,$00,$00,$00,$80,$c0,$c0,$e0 
        .byte $e0,$f0,$f0,$f0,$f0,$f0,$f0,$f0,$f0,$f0 
        .byte $f0,$f0,$f0,$f0,$f0,$f0,$f0,$f0,$f0,$e0 
        .byte $e0,$c0,$c0,$80,$00,$00,$00,$00,$00,$00

        .byte $01,$07,$0f,$3f,$3f,$7f,$ff,$ff,$ff,$ff 
        .byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff 
        .byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff 
        .byte $ff,$ff,$ff,$ff,$ff,$7f,$3f,$1f,$0f,$03

        .byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff 
        .byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff 
        .byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff 
        .byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff

        .byte $f0,$f0,$f0,$f0,$f0,$f0,$f0,$f0,$f0,$f0 
        .byte $f0,$f0,$f0,$f0,$f0,$f0,$f0,$f0,$f0,$f0 
        .byte $f0,$f0,$f0,$f0,$f0,$f0,$f0,$f0,$10,$00 
        .byte $80,$00,$10,$30,$f0,$f0,$f0,$f0,$f0,$f0

        .byte $c0,$f0,$fc,$fe,$ff,$ff,$ff,$ff,$ff,$ff 
        .byte $ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$fc 
        .byte $fb,$f7,$ef,$ff,$ff,$ff,$ff,$ff,$3f,$1f 
        .byte $1f,$9f,$3f,$7f,$ff,$ff,$ff,$fe,$fc,$f0

        .byte $00,$00,$00,$00,$00,$01,$07,$0f,$0f,$1f 
        .byte $1f,$3f,$3f,$3f,$7f,$ff,$ff,$ff,$ff,$80 
        .byte $ff,$ff,$ff,$ff,$ff,$7f,$7f,$3f,$3f,$1f 
        .byte $1f,$0f,$0f,$07,$03,$01,$00,$00,$00,$00
